### ISSUE TITLE
[FEATURE] - Get phone number when call incoming

### ISSUE THREAD

**Issue by Zounedou** [andreamainella98/phone_state#1]
Hi, I would like your plugins to return the phone number on each state change if possible.
Thanks.

**Comment by andreamainella98** [comment]
Hi @Zounedou, sorry for the delay, for this feature requested if I am not mistaken it would be possible to do it exclusively on android but not on ios, this is because apple, for privacy reasons, does not natively allow to obtain this information.
If I find a way to implement it, I will release a package update.

Thanks and I'm sorry for the delay again.

**Comment by hamzaydia** [comment]
I need to get the inbound/outbound call phone number at least in android, is there a way or a package?

**Comment by andreamainella98** [comment]
Duplicate #14
